version: '3.7'

networks:
  back_end:
    external: true

services:
  db:
    container_name: db_pharol
    image: mongo:latest
    ports:
      - 27018:27018
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_DATABASE=pharol_test
      - MONGO_INITDB_ROOT_USERNAME=pharol_user
      - MONGO_INITDB_ROOT_PASSWORD=root123asd
    networks: 
      - back_end
  api:
    container_name: apipharol
    image: apipharol
    build: 
      context: .
      target: base
    command: sh -c "npm install ; pm2-runtime ecosystem.config.json"
    volumes:
      - ./:/app
    ports:
      - 3002:3002
    depends_on:
      - db
    environment:
      - MONGO_INITDB_DATABASE=db_pharol
      - MONGO_INITDB_DATABASE=pharol_test
      - MONGO_INITDB_ROOT_USERNAME=pharol_user
      - MONGO_INITDB_ROOT_PASSWORD=root123asd
      - MONGO_PORT=27018
      - PORT=3002
      - NODE_ENV=development
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:apipharol.localhost
      - QUEUE_PREFIX=local
    networks: 
      - back_end
