version: '3.7'

networks:
  back_end:
    external: true
    driver: bridge

services:
  db:
    container_name: ${DB_HOST}
    image: bitnami/mongodb:3.6
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGODB_PORT_NUMBER=${MONGO_PORT}
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_USERNAME=${USERNAME}
      - MONGODB_PASSWORD=${PASSWORD}
    networks: 
      - back_end
  
  api:
    container_name: apipharol
    image: apipharol
    build: 
      context: .
      target: base
    command: sh -c "npm install ; pm2-runtime ecosystem.config.json"
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks: 
      - back_end
    environment:
      - MONGO_DB=${DB_NAME}
      - MONGO_USER=${USERNAME}
      - MONGO_PASSWORD=${PASSWORD}
      - MONGO_HOST=${DB_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - PORT=${API_PORT}
      - NODE_ENV=${ENV}
